import chicken1 from "../../../public/chicken1.png";
import chicken2 from "../../../public/chicken2.png";
import chicken3 from "../../../public/chicken3.png";
import chickenboneless from "../../../public/chickenboneless.jpg";
import goat1 from "../../../public/goat1.png";
import goat2 from "../../../public/goat2.png";
import mutton from "../../../public/mutonRaw.jpg";
import muttonKeema from "../../../public/mutton_keema.jpg";
import muttonliver from "../../../public/muttonliver.jpg";
import fish1 from "../../../public/fish1.png";
import fish2 from "../../../public/fish2.png";
import fish3 from "../../../public/fish3.png";
import fish4 from "../../../public/fish4.jpg";
import fish5 from "../../../public/fish5.jpg";
import oyester from "../../../public/oyster.webp";
import octupus from "../../../public/Octupus.webp";
import lobster from "../../../public/lobster.jpeg";
import squid from "../../../public/squid.jpeg";

export const items = [
  {
    id: 1,
    name: "Full chicken",
    image: chicken1,
    price: 500, // price for 1/2 kg
    price2: 900, // price for 1 kg
    oldPrice: 1040,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
  {
    id: 2,
    name: "Cooked chicken",
    image: chicken2,
    price: 300, // price for 1/2 kg
    price2: 500, // price for 1 kg
    oldPrice: 900,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "0.5kg",
    bgColor: "#FFF4C4",
  },
  {
    id: 3,
    name: "Chicken wings",
    image: chicken3,
    price: 160, // price for 1/2 kg
    price2: 500, // price for 1kg
    oldPrice: 210,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "0.5kg",
    bgColor: "#D7F5E9",
  },
  {
    id: 4,
    name: "Mutton",
    image: goat1,
    price: 350,
    price2: 500,
    oldPrice: 700,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#C9EEFF",
  },
  {
    id: 5,
    name: "Mutton",
    image: goat2,
    price: 350,
    price2: 500,
    oldPrice: 800,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 5,
    name: "Mutton",
    image: goat2,
    price: 350, // price for 1/2 kg
    price2: 500, // price for 1 kg
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 5,
    name: "Mutton",
    image: goat2,
    price: 350,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
];
export const polularItems = [
  {
    id: 1,
    name: "Full chicken",
    image: chicken1,
    price: 500, // price for 1/2 kg
    price2: 900, // price for 1 kg
    oldPrice: 1040,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
  {
    id: 2,
    name: "Bhangun Fish",
    image: fish1,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
  {
    id: 3,
    name: "Mutton",
    image: goat1,
    price: 350,
    price2: 500,
    oldPrice: 700,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#C9EEFF",
  },
  {
    id: 4,
    name: "Mutton kemma",
    image: goat2,
    price: 350, // price for 1/2 kg
    price2: 500, // price for 1 kg
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
];

export const fishMenu = [
  {
    id: 1,
    name: "Bhangun Fish",
    image: fish1,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
  {
    id: 2,
    name: "Bhokua",
    image: fish2,
    price: 910,
    price2: 1200,
    oldPrice: 1500,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#C9EEFF",
  },
  {
    id: 3,
    name: "Common Carp",
    image: fish3,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 4,
    name: "Rohu",
    image: fish4,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#D7F5E9",
  },
  {
    id: 5,
    name: "Prawns",
    image: fish1,
    price: 400,
    price2: 600,
    oldPrice: 900,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 6,
    name: "Prawns",
    image: fish5,
    price: 400,
    price2: 600,
    oldPrice: 900,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 7,
    name: "Prawns",
    image: fish2,
    price: 400,
    price2: 600,
    oldPrice: 900,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
];
export const chickenMenu = [
  {
    id: 1,
    name: "Chicken",
    image: chicken1,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
  {
    id: 2,
    name: "Chicken Boneless",
    image: chickenboneless,
    price: 910,
    price2: 1200,
    oldPrice: 1500,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#C9EEFF",
  },
  {
    id: 3,
    name: "Full Chicken",
    image: chicken2,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 4,
    name: "Chicken bone",
    image: chicken3,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#D7F5E9",
  },
  {
    id: 5,
    name: "Prawns",
    image: fish5,
    price: 400,
    price2: 600,
    oldPrice: 900,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 6,
    name: "Chicken liver",
    image: muttonliver,
    price: 400,
    price2: 600,
    oldPrice: 900,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
];
export const muttonMenu = [
  {
    id: 1,
    name: "Mutton",
    image: mutton,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
  {
    id: 2,
    name: "Mutton Bone",
    image: goat1,
    price: 910,
    price2: 1200,
    oldPrice: 1500,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#C9EEFF",
  },
  {
    id: 3,
    name: "Mutton keema",
    image: muttonKeema,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 4,
    name: "Mutton ",
    image: goat2,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#D7F5E9",
  },
  {
    id: 5,
    name: "Mutton liver",
    image: muttonliver,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#D7F5E9",
  },
  {
    id: 6,
    name: "Mutton",
    image: mutton,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
];
export const seafoodMenu = [
  {
    id: 1,
    name: "Oyester",
    image: oyester,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#F2E4FA",
  },
  {
    id: 2,
    name: "Lobster",
    image: lobster,
    price: 910,
    price2: 1200,
    oldPrice: 1500,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#C9EEFF",
  },
  {
    id: 3,
    name: "Octupus",
    image: octupus,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 4,
    name: "Squid",
    image: squid,
    price: 230,
    price2: 500,
    oldPrice: 400,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#D7F5E9",
  },
  {
    id: 5,
    name: "Prawns",
    image: fish5,
    price: 400,
    price2: 600,
    oldPrice: 900,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#f5c6ea",
  },
  {
    id: 6,
    name: "Fish",
    image: fish2,
    price: 910,
    price2: 1200,
    oldPrice: 1500,
    weights: ["1kg", "0.5kg"],
    defaultWeight: "1kg",
    bgColor: "#C9EEFF",
  },
];
